---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: document
  path: content/_index.md
  label: Home
- type: document
  path: content/about.md
  label: About
- type: document
  path: content/inquiries.md
  label: Inquiries
- type: directory
  path: content/portfolio
  label: Portfolio
  create: documents
  match: "**/*"
  templates:
  - landing-page
- type: directory
  path: content/journal
  label: Journal
  create: all
  match: "**/*"
  templates:
  - blog-post
- type: document
  path: content/alerts.md
  label: Alerts
upload_dir: assets/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.80.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.80.0
